# Generated by Django 3.2.8 on 2021-10-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_alter_venda_data_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='preco_final',
            field=models.FloatField(default=0),
        ),
    ]
