# Generated by Django 3.2.8 on 2021-10-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
